export type FeedVideo = {
  id: string;
  sourceId?: "internet-archive" | "wikimedia" | "wikimedia-commons" | "nasa" | "peertube" | "youtube" | "twitch" | "pexels" | "pixabay" | "dailymotion" | "blender" | "ihavenotv" | "free-stock";
  channelId?: string;
  creatorUrl?: string;
  title: string;
  channelTitle: string;
  thumbnail: string;
  publishedAt: string;
  viewCount: string;
  duration: string;
  concurrentViewers?: string;
  category?: string;
  creator?: string;
  license?: string;
  licenseUrl?: string;
  sourceName?: string;
  sourceUrl?: string;
  thumbnailAttribution?: string;
  videoUrl?: string;
  embedUrl?: string;
  description?: string;
};

export const devFeedVideos: FeedVideo[] = [
  {
    id: "qciHPEHxUAo",
    sourceId: "youtube",
    title: "Dile A Tu Gato Hoodtrap",
    channelTitle: "Thery - Topic",
    thumbnail: "https://i.ytimg.com/vi/qciHPEHxUAo/maxresdefault.jpg",
    publishedAt: "2026-09-06T14:00:17Z",
    viewCount: "116657",
    duration: "PT1M35S",
  },
  {
    id: "vw0mF5a7_dI",
    sourceId: "youtube",
    title: "FOCKER IN-LAW Trailer 2 (2026) Ariana Grande, Ben Stiller",
    channelTitle: "Entertainment Access",
    thumbnail: "https://i.ytimg.com/vi/vw0mF5a7_dI/maxresdefault.jpg",
    publishedAt: "2026-09-04T16:16:44Z",
    viewCount: "345032",
    duration: "PT2M46S",
  },
  {
    id: "we2dBzQxtgQ",
    sourceId: "youtube",
    title: "1000 Players Simulate Mining Prison in Minecraft",
    channelTitle: "Parrot",
    thumbnail: "https://i.ytimg.com/vi/we2dBzQxtgQ/maxresdefault.jpg",
    publishedAt: "2026-09-05T13:00:30Z",
    viewCount: "4805855",
    duration: "PT2H12M13S",
  },
  {
    id: "FyS5dAywkEo",
    sourceId: "youtube",
    title: "LISA - SaWaDiKa (Official Music Video)",
    channelTitle: "LISAOfficialVEVO",
    thumbnail: "https://i.ytimg.com/vi/FyS5dAywkEo/maxresdefault.jpg",
    publishedAt: "2026-09-04T00:00:05Z",
    viewCount: "127311962",
    duration: "PT3M7S",
  },
  {
    id: "pzXW1FydqnE",
    sourceId: "youtube",
    title: "Myriad Celestia Trailer: \"Deep Waters\" | Honkai: Star Rail",
    channelTitle: "Honkai: Star Rail",
    thumbnail: "https://i.ytimg.com/vi/pzXW1FydqnE/maxresdefault.jpg",
    publishedAt: "2026-09-06T04:00:26Z",
    viewCount: "343613",
    duration: "PT4M2S",
  },
  {
    id: "IsxOGgWs2Dk",
    sourceId: "youtube",
    title: "NOOB vs PRO Island House Competition!",
    channelTitle: "Cash",
    thumbnail: "https://i.ytimg.com/vi/IsxOGgWs2Dk/maxresdefault.jpg",
    publishedAt: "2026-09-06T15:00:10Z",
    viewCount: "281021",
    duration: "PT20M39S",
  },
  {
    id: "GPb7pwHIDx4",
    sourceId: "youtube",
    title: "Jarahn x SHLD - Yu Les (Audio) feat. Nene Morus & Rich Antony",
    channelTitle: "Jarahn",
    thumbnail: "https://i.ytimg.com/vi/GPb7pwHIDx4/maxresdefault.jpg",
    publishedAt: "2026-08-27T16:14:51Z",
    viewCount: "83203",
    duration: "PT4M2S",
  },
  {
    id: "P9BsjBrHhE4",
    sourceId: "youtube",
    title: "how i outsmarted 500 people for $10,000",
    channelTitle: "JudeLow",
    thumbnail: "https://i.ytimg.com/vi/P9BsjBrHhE4/maxresdefault.jpg",
    publishedAt: "2026-09-06T03:43:26Z",
    viewCount: "1705444",
    duration: "PT35M21S",
  },
  {
    id: "7xYekUcLRs4",
    sourceId: "youtube",
    title: "Libera Me From Hell - Mori Calliope x Elizabeth Rose Bloodflame // GURREN LAGANN (Cover)",
    channelTitle: "Mori Calliope Ch. hololive-EN",
    thumbnail: "https://i.ytimg.com/vi/7xYekUcLRs4/maxresdefault.jpg",
    publishedAt: "2026-09-06T03:00:06Z",
    viewCount: "773861",
    duration: "PT4M46S",
  },
  {
    id: "gTHQuqtAsM0",
    sourceId: "youtube",
    title: "SILO Season 4 Trailer Breakdown",
    channelTitle: "Pete Peppers",
    thumbnail: "https://i.ytimg.com/vi/gTHQuqtAsM0/maxresdefault.jpg",
    publishedAt: "2026-09-05T17:47:54Z",
    viewCount: "198559",
    duration: "PT14M21S",
  },
  {
    id: "GM6J-upDNYw",
    sourceId: "youtube",
    title: "3 SCARY GAMES #114",
    channelTitle: "Markiplier",
    thumbnail: "https://i.ytimg.com/vi/GM6J-upDNYw/maxresdefault.jpg",
    publishedAt: "2026-09-05T18:47:38Z",
    viewCount: "1252525",
    duration: "PT1H3M43S",
  },
  {
    id: "MLKyjv0Rmu4",
    sourceId: "youtube",
    title: "Le Dicen",
    channelTitle: "Grupo Recluta - Topic",
    thumbnail: "https://i.ytimg.com/vi/MLKyjv0Rmu4/maxresdefault.jpg",
    publishedAt: "2026-09-06T02:01:59Z",
    viewCount: "17809",
    duration: "PT2M52S",
  },
  {
    id: "x1jT51-fF3I",
    sourceId: "youtube",
    title: "The Biggest Takeaways From the New Harry Potter HBO Series Trailer",
    channelTitle: "MovieFlame",
    thumbnail: "https://i.ytimg.com/vi/x1jT51-fF3I/maxresdefault.jpg",
    publishedAt: "2026-09-06T15:37:59Z",
    viewCount: "53379",
    duration: "PT16M23S",
  },
  {
    id: "0kha6J1erqs",
    sourceId: "youtube",
    title: "How I Won A $10,000 Rainbow Tournament.",
    channelTitle: "Joe Bart Games",
    thumbnail: "https://i.ytimg.com/vi/0kha6J1erqs/maxresdefault.jpg",
    publishedAt: "2026-09-06T16:25:20Z",
    viewCount: "135842",
    duration: "PT50M20S",
  },
  {
    id: "4Z_omCqDgM0",
    sourceId: "youtube",
    title: "NASA's SpaceX Crew-9 Mission Prelaunch",
    channelTitle: "NASA",
    thumbnail: "https://i.ytimg.com/vi/4Z_omCqDgM0/hqdefault.jpg",
    publishedAt: "2026-09-09T18:00:00Z",
    viewCount: "258630",
    duration: "PT8M21S",
  },
  {
    id: "xE6vE6-K9cA",
    sourceId: "youtube",
    title: "The Art of Creative Coding in 10 Minutes",
    channelTitle: "Coding with Chris",
    thumbnail: "https://i.ytimg.com/vi/xE6vE6-K9cA/hqdefault.jpg",
    publishedAt: "2026-09-08T11:25:00Z",
    viewCount: "92430",
    duration: "PT10M07S",
  },
  {
    id: "nasa-earthrise",
    sourceId: "nasa",
    title: "Earthrise from Apollo 8",
    channelTitle: "NASA",
    thumbnail: "https://images-assets.nasa.gov/image/iss065e056904/iss065e056904~medium.jpg",
    publishedAt: "1968-12-24T00:00:00Z",
    viewCount: "480000",
    duration: "PT1M30S",
    creator: "NASA / Apollo 8",
    license: "Public domain",
    sourceName: "NASA",
    sourceUrl: "https://www.nasa.gov/",
    thumbnailAttribution: "NASA",
    videoUrl: "https://images-assets.nasa.gov/video/iss065e056904/iss065e056904~orig.mp4",
  },
  {
    id: "wikimedia-aurora",
    sourceId: "wikimedia-commons",
    title: "Aurora over Iceland",
    channelTitle: "Wikimedia Commons",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Aurora_2013_II.jpg/800px-Aurora_2013_II.jpg",
    publishedAt: "2013-02-14T00:00:00Z",
    viewCount: "31000",
    duration: "PT2M15S",
    creator: "Wikimedia Commons contributor",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/",
    thumbnailAttribution: "Wikimedia Commons",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9d/Example.ogv/Example.ogv.360p.webm",
  },
  {
    id: "peertube-skywatch",
    sourceId: "peertube",
    title: "Night Sky Time Lapse",
    channelTitle: "Open Sky Archive",
    thumbnail: "https://peertube.tv/static/peertube-banner.png",
    publishedAt: "2026-09-03T20:30:00Z",
    viewCount: "24510",
    duration: "PT4M40S",
    creator: "Open Sky Archive",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceName: "PeerTube",
    sourceUrl: "https://peertube.tv/",
    thumbnailAttribution: "PeerTube",
    videoUrl: "https://peertube.tv/static/placeholder-video.mp4",
  },
  {
    id: "peertube-forest-sound",
    sourceId: "peertube",
    title: "Forest Soundscapes at Dawn",
    channelTitle: "Eco Cinema",
    thumbnail: "https://peertube.tv/static/peertube-banner.png",
    publishedAt: "2026-09-12T06:15:00Z",
    viewCount: "18240",
    duration: "PT7M10S",
    creator: "Eco Cinema",
    license: "CC BY 4.0",
    sourceName: "PeerTube",
    sourceUrl: "https://peertube.tv/",
    thumbnailAttribution: "PeerTube",
    videoUrl: "https://peertube.tv/static/placeholder-video.mp4",
  },
  {
    id: "peertube-city-rail",
    sourceId: "peertube",
    title: "City Rail Documentary",
    channelTitle: "Transit Frames",
    thumbnail: "https://peertube.tv/static/peertube-banner.png",
    publishedAt: "2026-09-11T19:45:00Z",
    viewCount: "22150",
    duration: "PT11M20S",
    creator: "Transit Frames",
    license: "CC BY 4.0",
    sourceName: "PeerTube",
    sourceUrl: "https://peertube.tv/",
    thumbnailAttribution: "PeerTube",
    videoUrl: "https://peertube.tv/static/placeholder-video.mp4",
  },
  {
    id: "peertube-ocean-depths",
    sourceId: "peertube",
    title: "Ocean Depths: Blue Hour",
    channelTitle: "Deep Blue Archive",
    thumbnail: "https://peertube.tv/static/peertube-banner.png",
    publishedAt: "2026-09-10T21:30:00Z",
    viewCount: "19680",
    duration: "PT9M05S",
    creator: "Deep Blue Archive",
    license: "CC BY 4.0",
    sourceName: "PeerTube",
    sourceUrl: "https://peertube.tv/",
    thumbnailAttribution: "PeerTube",
    videoUrl: "https://peertube.tv/static/placeholder-video.mp4",
  },
  {
    id: "dailymotion-solar-farm",
    sourceId: "dailymotion",
    title: "Solar Farm Timelapse",
    channelTitle: "Future Energy",
    thumbnail: "https://static1.dmcdn.net/teasers/solar-farm.jpg",
    publishedAt: "2026-09-12T08:00:00Z",
    viewCount: "21430",
    duration: "PT5M12S",
    creator: "Future Energy",
    license: "CC BY 4.0",
    sourceName: "Dailymotion",
    sourceUrl: "https://www.dailymotion.com/video/x8k7d8q",
    thumbnailAttribution: "Dailymotion",
    embedUrl: "https://geo.dailymotion.com/player.html?video=x8k7d8q",
  },
  {
    id: "dailymotion-cooking-demo",
    sourceId: "dailymotion",
    title: "Street Food Cooking Demo",
    channelTitle: "Chef Lab",
    thumbnail: "https://static1.dmcdn.net/teasers/cooking-demo.jpg",
    publishedAt: "2026-09-11T16:00:00Z",
    viewCount: "18810",
    duration: "PT6M40S",
    creator: "Chef Lab",
    license: "CC BY 4.0",
    sourceName: "Dailymotion",
    sourceUrl: "https://www.dailymotion.com/video/x8k7d8r",
    thumbnailAttribution: "Dailymotion",
    embedUrl: "https://geo.dailymotion.com/player.html?video=x8k7d8r",
  },
  {
    id: "dailymotion-sky-diving",
    sourceId: "dailymotion",
    title: "Skydiving Highlights",
    channelTitle: "Aerial Concepts",
    thumbnail: "https://static1.dmcdn.net/teasers/skydiving.jpg",
    publishedAt: "2026-09-10T12:00:00Z",
    viewCount: "33290",
    duration: "PT8M15S",
    creator: "Aerial Concepts",
    license: "CC BY 4.0",
    sourceName: "Dailymotion",
    sourceUrl: "https://www.dailymotion.com/video/x8k7d8s",
    thumbnailAttribution: "Dailymotion",
    embedUrl: "https://geo.dailymotion.com/player.html?video=x8k7d8s",
  },
  {
    id: "gkKJSkT9X9A",
    sourceId: "youtube",
    title: "Best Open World Games of the Year",
    channelTitle: "Game Radar",
    thumbnail: "https://i.ytimg.com/vi/gkKJSkT9X9A/hqdefault.jpg",
    publishedAt: "2026-09-11T13:45:00Z",
    viewCount: "866500",
    duration: "PT15M48S",
  },
  {
    id: "rN6P7n5mR1A",
    sourceId: "youtube",
    title: "City Walkthrough Timelapse at Golden Hour",
    channelTitle: "Urban Lens",
    thumbnail: "https://i.ytimg.com/vi/rN6P7n5mR1A/hqdefault.jpg",
    publishedAt: "2026-09-10T08:02:00Z",
    viewCount: "174820",
    duration: "PT6M12S",
  },
  {
    id: "internet-archive-astronomy",
    sourceId: "internet-archive",
    title: "Solar System Overview",
    channelTitle: "Internet Archive Education",
    thumbnail: "https://archive.org/services/img/solar-system-overview",
    publishedAt: "2015-01-20T00:00:00Z",
    viewCount: "9200",
    duration: "PT5M00S",
    creator: "Internet Archive",
    license: "Public domain",
    sourceName: "Internet Archive",
    sourceUrl: "https://archive.org/",
    thumbnailAttribution: "Internet Archive",
    videoUrl: "https://archive.org/download/solar-system-overview/solar-system-overview.mp4",
  },
  {
    id: "R1v6n9aM6vE",
    sourceId: "youtube",
    title: "The Best Sci-Fi Short Films You Need to Watch",
    channelTitle: "CineScope",
    thumbnail: "https://i.ytimg.com/vi/R1v6n9aM6vE/hqdefault.jpg",
    publishedAt: "2026-09-09T10:15:00Z",
    viewCount: "318400",
    duration: "PT13M42S",
  },
  {
    id: "3XjL1v7kTq4",
    sourceId: "youtube",
    title: "Top 10 Hidden Gems in Indie Games",
    channelTitle: "Gamer's Digest",
    thumbnail: "https://i.ytimg.com/vi/3XjL1v7kTq4/hqdefault.jpg",
    publishedAt: "2026-09-08T18:35:00Z",
    viewCount: "540220",
    duration: "PT11M09S",
  },
  {
    id: "2Lq0rSx4T7k",
    sourceId: "youtube",
    title: "Modern Architecture Tour: City Lines",
    channelTitle: "Design Frame",
    thumbnail: "https://i.ytimg.com/vi/2Lq0rSx4T7k/hqdefault.jpg",
    publishedAt: "2026-09-07T11:00:00Z",
    viewCount: "192800",
    duration: "PT9M51S",
  },
  {
    id: "w7Bz4x9N2uM",
    sourceId: "youtube",
    title: "The Rise of AI Art Tools Explained",
    channelTitle: "Future Signals",
    thumbnail: "https://i.ytimg.com/vi/w7Bz4x9N2uM/hqdefault.jpg",
    publishedAt: "2026-09-06T07:45:00Z",
    viewCount: "815300",
    duration: "PT16M33S",
  },
  {
    id: "m4YQn6eT2qP",
    sourceId: "youtube",
    title: "Travel Vlog: 24 Hours in Kyoto",
    channelTitle: "Nomad Frames",
    thumbnail: "https://i.ytimg.com/vi/m4YQn6eT2qP/hqdefault.jpg",
    publishedAt: "2026-09-05T16:12:00Z",
    viewCount: "463100",
    duration: "PT18M07S",
  },
  {
    id: "nasa-aurora",
    sourceId: "nasa",
    title: "Aurora Time Lapse from the ISS",
    channelTitle: "NASA",
    thumbnail: "https://images-assets.nasa.gov/image/iss056e085682/iss056e085682~medium.jpg",
    publishedAt: "2026-09-02T00:00:00Z",
    viewCount: "196000",
    duration: "PT2M30S",
    creator: "NASA",
    license: "Public domain",
    sourceName: "NASA",
    sourceUrl: "https://www.nasa.gov/",
    thumbnailAttribution: "NASA",
    videoUrl: "https://images-assets.nasa.gov/video/iss056e085682/iss056e085682~orig.mp4",
  },
  {
    id: "commons-frog",
    sourceId: "wikimedia-commons",
    title: "Frog Habitat Time Lapse",
    channelTitle: "Wikimedia Commons",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Common_frog_2.jpg/800px-Common_frog_2.jpg",
    publishedAt: "2026-09-01T09:00:00Z",
    viewCount: "28700",
    duration: "PT3M44S",
    creator: "Wikimedia contributor",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/",
    thumbnailAttribution: "Wikimedia Commons",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/54/Example.ogv/Example.ogv.360p.webm",
  },
  {
    id: "peertube-studio",
    sourceId: "peertube",
    title: "Creative Studio Session 2026",
    channelTitle: "Open Studio Network",
    thumbnail: "https://peertube.tv/static/peertube-banner.png",
    publishedAt: "2026-08-28T14:40:00Z",
    viewCount: "14830",
    duration: "PT6M18S",
    creator: "Open Studio Network",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceName: "PeerTube",
    sourceUrl: "https://peertube.tv/",
    thumbnailAttribution: "PeerTube",
    videoUrl: "https://peertube.tv/static/placeholder-video.mp4",
  },
  {
    id: "N2kQ7hY9b5c",
    sourceId: "youtube",
    title: "I Built a Tiny Home Studio for a Week",
    channelTitle: "Minimal Living",
    thumbnail: "https://i.ytimg.com/vi/N2kQ7hY9b5c/hqdefault.jpg",
    publishedAt: "2026-08-30T12:00:00Z",
    viewCount: "382600",
    duration: "PT21M10S",
  },
  {
    id: "C8vL2xR6p4m",
    sourceId: "youtube",
    title: "Street Food Tour in Seoul",
    channelTitle: "Flavor Drift",
    thumbnail: "https://i.ytimg.com/vi/C8vL2xR6p4m/hqdefault.jpg",
    publishedAt: "2026-08-29T19:03:00Z",
    viewCount: "271700",
    duration: "PT12M28S",
  },
  {
    id: "T7gR4sE9q1a",
    sourceId: "youtube",
    title: "Behind the Scenes of a 3D Animation Pipeline",
    channelTitle: "VFX Lab",
    thumbnail: "https://i.ytimg.com/vi/T7gR4sE9q1a/hqdefault.jpg",
    publishedAt: "2026-08-27T09:50:00Z",
    viewCount: "688500",
    duration: "PT15M24S",
  },
  {
    id: "dQw4w9WgXcQ",
    sourceId: "youtube",
    title: "Never Gonna Give You Up",
    channelTitle: "Rick Astley",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    publishedAt: "2026-08-26T12:00:00Z",
    viewCount: "1500000000",
    duration: "PT3M33S",
  },
  {
    id: "9bZkp7q19f0",
    sourceId: "youtube",
    title: "Gangnam Style",
    channelTitle: "officialpsy",
    thumbnail: "https://i.ytimg.com/vi/9bZkp7q19f0/hqdefault.jpg",
    publishedAt: "2026-08-25T12:00:00Z",
    viewCount: "5200000000",
    duration: "PT4M13S",
  },
  {
    id: "kJQP7kiw5Fk",
    sourceId: "youtube",
    title: "Despacito",
    channelTitle: "Luis Fonsi",
    thumbnail: "https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg",
    publishedAt: "2026-08-24T12:00:00Z",
    viewCount: "8500000000",
    duration: "PT4M42S",
  },
  {
    id: "3JZ_D3ELwOQ",
    sourceId: "youtube",
    title: "See You Again",
    channelTitle: "Wiz Khalifa",
    thumbnail: "https://i.ytimg.com/vi/3JZ_D3ELwOQ/hqdefault.jpg",
    publishedAt: "2026-08-23T12:00:00Z",
    viewCount: "6500000000",
    duration: "PT3M58S",
  },
  {
    id: "L_jWHffIx5E",
    sourceId: "youtube",
    title: "All Star",
    channelTitle: "Smash Mouth",
    thumbnail: "https://i.ytimg.com/vi/L_jWHffIx5E/hqdefault.jpg",
    publishedAt: "2026-08-22T12:00:00Z",
    viewCount: "500000000",
    duration: "PT4M2S",
  },
  {
    id: "hTWKbfoikeg",
    sourceId: "youtube",
    title: "Smells Like Teen Spirit",
    channelTitle: "Nirvana",
    thumbnail: "https://i.ytimg.com/vi/hTWKbfoikeg/hqdefault.jpg",
    publishedAt: "2026-08-21T12:00:00Z",
    viewCount: "1900000000",
    duration: "PT4M39S",
  },
  {
    id: "y6120QOlsfU",
    sourceId: "youtube",
    title: "Sandstorm",
    channelTitle: "Darude",
    thumbnail: "https://i.ytimg.com/vi/y6120QOlsfU/hqdefault.jpg",
    publishedAt: "2026-08-20T12:00:00Z",
    viewCount: "250000000",
    duration: "PT3M45S",
  },
  {
    id: "OPf0YbXqDm0",
    sourceId: "youtube",
    title: "Uptown Funk",
    channelTitle: "Mark Ronson",
    thumbnail: "https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg",
    publishedAt: "2026-08-19T12:00:00Z",
    viewCount: "5200000000",
    duration: "PT4M31S",
  },
  {
    id: "dailymotion-archaeology",
    sourceId: "dailymotion",
    title: "Ancient Ruins Walkthrough",
    channelTitle: "History Vault",
    thumbnail: "https://static1.dmcdn.net/teasers/archaeology.jpg",
    publishedAt: "2026-08-18T13:00:00Z",
    viewCount: "27420",
    duration: "PT9M25S",
    creator: "History Vault",
    license: "CC BY 4.0",
    sourceName: "Dailymotion",
    sourceUrl: "https://www.dailymotion.com/video/x8k7d8t",
    thumbnailAttribution: "Dailymotion",
    embedUrl: "https://geo.dailymotion.com/player.html?video=x8k7d8t",
  },
  {
    id: "dailymotion-robotics",
    sourceId: "dailymotion",
    title: "Robotics Classroom Demo",
    channelTitle: "Build Lab",
    thumbnail: "https://static1.dmcdn.net/teasers/robotics.jpg",
    publishedAt: "2026-08-17T17:00:00Z",
    viewCount: "24410",
    duration: "PT7M48S",
    creator: "Build Lab",
    license: "CC BY 4.0",
    sourceName: "Dailymotion",
    sourceUrl: "https://www.dailymotion.com/video/x8k7d8u",
    thumbnailAttribution: "Dailymotion",
    embedUrl: "https://geo.dailymotion.com/player.html?video=x8k7d8u",
  },
  {
    id: "dailymotion-nature-trail",
    sourceId: "dailymotion",
    title: "Nature Trail Discovery",
    channelTitle: "Wild Lens",
    thumbnail: "https://static1.dmcdn.net/teasers/nature-trail.jpg",
    publishedAt: "2026-08-16T07:00:00Z",
    viewCount: "20950",
    duration: "PT6M28S",
    creator: "Wild Lens",
    license: "CC BY 4.0",
    sourceName: "Dailymotion",
    sourceUrl: "https://www.dailymotion.com/video/x8k7d8v",
    thumbnailAttribution: "Dailymotion",
    embedUrl: "https://geo.dailymotion.com/player.html?video=x8k7d8v",
  },
];
