import type { FeedVideo } from "@/lib/feed-videos";

const baseUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample";

const freeStockVideos: FeedVideo[] = [
  {
    id: "free-stock-big-buck-bunny",
    sourceId: "free-stock",
    title: "Big Buck Bunny",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/BigBuckBunny.jpg`,
    publishedAt: "2024-01-01T00:00:00Z",
    viewCount: "1320000",
    duration: "PT10M34S",
    category: "Animation",
    creator: "Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/BigBuckBunny.mp4`,
  },
  {
    id: "free-stock-elephants-dream",
    sourceId: "free-stock",
    title: "Elephants Dream",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/ElephantsDream.jpg`,
    publishedAt: "2024-01-02T00:00:00Z",
    viewCount: "980000",
    duration: "PT10M54S",
    category: "Sci-fi",
    creator: "Orange Open Movie Project",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/ElephantsDream.mp4`,
  },
  {
    id: "free-stock-sintel",
    sourceId: "free-stock",
    title: "Sintel",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/Sintel.jpg`,
    publishedAt: "2024-01-03T00:00:00Z",
    viewCount: "740000",
    duration: "PT14M48S",
    category: "Fantasy",
    creator: "Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/Sintel.mp4`,
  },
  {
    id: "free-stock-tears-of-steel",
    sourceId: "free-stock",
    title: "Tears of Steel",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/TearsOfSteel.jpg`,
    publishedAt: "2024-01-04T00:00:00Z",
    viewCount: "860000",
    duration: "PT12M14S",
    category: "Action",
    creator: "Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/TearsOfSteel.mp4`,
  },
  {
    id: "free-stock-for-bigger-blazes",
    sourceId: "free-stock",
    title: "For Bigger Blazes",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/ForBiggerBlazes.jpg`,
    publishedAt: "2024-01-05T00:00:00Z",
    viewCount: "2650000",
    duration: "PT15S",
    category: "Action",
    creator: "Google Sample Videos",
    license: "Public domain demo footage",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/ForBiggerBlazes.mp4`,
  },
  {
    id: "free-stock-for-bigger-escapes",
    sourceId: "free-stock",
    title: "For Bigger Escapes",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/ForBiggerEscapes.jpg`,
    publishedAt: "2024-01-06T00:00:00Z",
    viewCount: "2120000",
    duration: "PT15S",
    category: "Adventure",
    creator: "Google Sample Videos",
    license: "Public domain demo footage",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/ForBiggerEscapes.mp4`,
  },
  {
    id: "free-stock-for-bigger-fun",
    sourceId: "free-stock",
    title: "For Bigger Fun",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/ForBiggerFun.jpg`,
    publishedAt: "2024-01-07T00:00:00Z",
    viewCount: "1890000",
    duration: "PT15S",
    category: "Comedy",
    creator: "Google Sample Videos",
    license: "Public domain demo footage",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/ForBiggerFun.mp4`,
  },
  {
    id: "free-stock-for-bigger-joyrides",
    sourceId: "free-stock",
    title: "For Bigger Joyrides",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/ForBiggerJoyrides.jpg`,
    publishedAt: "2024-01-08T00:00:00Z",
    viewCount: "1430000",
    duration: "PT15S",
    category: "Travel",
    creator: "Google Sample Videos",
    license: "Public domain demo footage",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/ForBiggerJoyrides.mp4`,
  },
  {
    id: "free-stock-for-bigger-meltdowns",
    sourceId: "free-stock",
    title: "For Bigger Meltdowns",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/ForBiggerMeltdowns.jpg`,
    publishedAt: "2024-01-09T00:00:00Z",
    viewCount: "1215000",
    duration: "PT15S",
    category: "Comedy",
    creator: "Google Sample Videos",
    license: "Public domain demo footage",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/ForBiggerMeltdowns.mp4`,
  },
  {
    id: "free-stock-subaru-outback",
    sourceId: "free-stock",
    title: "Subaru Outback on Street and Dirt",
    channelTitle: "Google Sample Videos",
    thumbnail: `${baseUrl}/images/SubaruOutbackOnStreetAndDirt.jpg`,
    publishedAt: "2024-01-10T00:00:00Z",
    viewCount: "910000",
    duration: "PT20S",
    category: "Driving",
    creator: "Google Sample Videos",
    license: "Public domain demo footage",
    sourceName: "Google Sample Videos",
    sourceUrl: "https://developers.google.com/",
    thumbnailAttribution: "Google Sample Videos",
    videoUrl: `${baseUrl}/SubaruOutbackOnStreetAndDirt.mp4`,
  },
  {
    id: "free-stock-spring-shot",
    sourceId: "free-stock",
    title: "Spring Nature Loop",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-11T00:00:00Z",
    viewCount: "684000",
    duration: "PT1M12S",
    category: "Nature",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853889/853889-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-ocean-drift",
    sourceId: "free-stock",
    title: "Ocean Drift",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-12T00:00:00Z",
    viewCount: "709000",
    duration: "PT1M08S",
    category: "Ocean",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/855104/855104-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-city-at-night",
    sourceId: "free-stock",
    title: "City at Night",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-13T00:00:00Z",
    viewCount: "612000",
    duration: "PT1M22S",
    category: "City",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853891/853891-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-mountain-ride",
    sourceId: "free-stock",
    title: "Mountain Ride",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-14T00:00:00Z",
    viewCount: "518000",
    duration: "PT1M18S",
    category: "Travel",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/854128/854128-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-lush-forest",
    sourceId: "free-stock",
    title: "Lush Forest",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-15T00:00:00Z",
    viewCount: "566000",
    duration: "PT1M09S",
    category: "Nature",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853999/853999-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-forest-stream",
    sourceId: "free-stock",
    title: "Forest Stream",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-16T00:00:00Z",
    viewCount: "403000",
    duration: "PT1M11S",
    category: "Nature",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/855287/855287-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-desert-dunes",
    sourceId: "free-stock",
    title: "Desert Dunes",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-17T00:00:00Z",
    viewCount: "485000",
    duration: "PT1M05S",
    category: "Landscape",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/854192/854192-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-skyline-sunset",
    sourceId: "free-stock",
    title: "Skyline Sunset",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-18T00:00:00Z",
    viewCount: "432000",
    duration: "PT1M03S",
    category: "Cityscape",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853744/853744-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-urban-lights",
    sourceId: "free-stock",
    title: "Urban Lights",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-19T00:00:00Z",
    viewCount: "391000",
    duration: "PT1M16S",
    category: "Nightlife",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853755/853755-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-coastal-drive",
    sourceId: "free-stock",
    title: "Coastal Drive",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-20T00:00:00Z",
    viewCount: "547000",
    duration: "PT1M09S",
    category: "Travel",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853930/853930-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-campfire-glow",
    sourceId: "free-stock",
    title: "Campfire Glow",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1504851149312-7a075b496cc7?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-21T00:00:00Z",
    viewCount: "365000",
    duration: "PT1M21S",
    category: "Lifestyle",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/854198/854198-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-snowy-road",
    sourceId: "free-stock",
    title: "Snowy Road",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1482192505345-5655af888cc4?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-22T00:00:00Z",
    viewCount: "319000",
    duration: "PT1M24S",
    category: "Roadtrip",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/854215/854215-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-river-drift",
    sourceId: "free-stock",
    title: "River Drift",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-23T00:00:00Z",
    viewCount: "294000",
    duration: "PT1M14S",
    category: "Water",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853886/853886-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-desert-sunset",
    sourceId: "free-stock",
    title: "Desert Sunset",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-24T00:00:00Z",
    viewCount: "277000",
    duration: "PT1M12S",
    category: "Desert",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/854136/854136-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-farm-fields",
    sourceId: "free-stock",
    title: "Farm Fields",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-25T00:00:00Z",
    viewCount: "236000",
    duration: "PT1M05S",
    category: "Farming",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853800/853800-hd_1920_1080_25fps.mp4",
  },
  {
    id: "free-stock-aurora-night",
    sourceId: "free-stock",
    title: "Aurora Night",
    channelTitle: "Open Stock Pack",
    thumbnail: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2024-01-26T00:00:00Z",
    viewCount: "254000",
    duration: "PT1M19S",
    category: "Night sky",
    creator: "Open stock repack",
    license: "Royalty-free preview",
    sourceName: "Open Stock Pack",
    sourceUrl: "https://unsplash.com/",
    thumbnailAttribution: "Unsplash",
    videoUrl: "https://videos.pexels.com/video-files/853730/853730-hd_1920_1080_25fps.mp4",
  },
];

export function getFreeVideoPool(): FeedVideo[] {
  return [...freeStockVideos];
}

export function paginateFreeVideos({
  page,
  limit,
  query,
}: {
  page: number;
  limit: number;
  query?: string | null;
}) {
  const normalizedQuery = query?.trim().toLowerCase();
  const items = normalizedQuery
    ? freeStockVideos.filter((video) => `${video.title} ${video.channelTitle}`.toLowerCase().includes(normalizedQuery))
    : freeStockVideos;

  const start = Math.max(page - 1, 0) * limit;
  const videos = items.slice(start, start + limit);

  return {
    videos,
    hasMore: start + limit < items.length,
  };
}
