import type { FeedVideo } from "@/lib/feed-videos";

const blenderLicenseUrl = "https://creativecommons.org/licenses/by/3.0/";

export const openFeedVideos: FeedVideo[] = [
  {
    id: "big-buck-bunny",
    title: "Big Buck Bunny",
    channelTitle: "Blender Open Movies",
    thumbnail: "https://archive.org/download/BigBuckBunny_328/__ia_thumb.jpg",
    publishedAt: "2008-04-10T00:00:00Z",
    viewCount: "0",
    duration: "PT9M56S",
    category: "Nature",
    creator: "Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: blenderLicenseUrl,
    sourceName: "Internet Archive / Blender Open Movies",
    sourceUrl: "https://archive.org/details/BigBuckBunny_328",
    thumbnailAttribution: "Blender Foundation via Internet Archive",
    videoUrl: "https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4",
  },
  {
    id: "sintel",
    title: "Sintel",
    channelTitle: "Blender Open Movies",
    thumbnail: "https://archive.org/download/Sintel/__ia_thumb.jpg",
    publishedAt: "2010-05-20T00:00:00Z",
    viewCount: "0",
    duration: "PT14M48S",
    category: "History",
    creator: "Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: blenderLicenseUrl,
    sourceName: "Internet Archive / Blender Open Movies",
    sourceUrl: "https://archive.org/details/Sintel",
    thumbnailAttribution: "Blender Foundation via Internet Archive",
    videoUrl: "https://archive.org/download/Sintel/sintel-2048-stereo_512kb.mp4",
  },
  {
    id: "cosmos-laundromat",
    title: "Cosmos Laundromat",
    channelTitle: "Blender Open Movies",
    thumbnail: "https://archive.org/download/cosmos-laundromat-first-cycle/CosmosLaundromatPoster_thumb.jpg",
    publishedAt: "2015-08-10T00:00:00Z",
    viewCount: "0",
    duration: "PT12M10S",
    category: "Science",
    creator: "Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: blenderLicenseUrl,
    sourceName: "Internet Archive / Blender Open Movies",
    sourceUrl: "https://archive.org/details/cosmos-laundromat-first-cycle",
    thumbnailAttribution: "Blender Foundation via Internet Archive",
    videoUrl: "https://archive.org/download/cosmos-laundromat-first-cycle/Cosmos%20Laundromat%20-%20First%20Cycle.mp4",
  },
  {
    id: "caminandes-lamigos",
    title: "Caminandes: Llamigos",
    channelTitle: "Blender Open Movies",
    thumbnail: "https://archive.org/download/CaminandesLlamigos/__ia_thumb.jpg",
    publishedAt: "2013-12-10T00:00:00Z",
    viewCount: "0",
    duration: "PT2M30S",
    category: "Nature",
    creator: "Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: blenderLicenseUrl,
    sourceName: "Internet Archive / Blender Open Movies",
    sourceUrl: "https://archive.org/details/CaminandesLlamigos",
    thumbnailAttribution: "Blender Foundation via Internet Archive",
    videoUrl: "https://archive.org/download/CaminandesLlamigos/Caminandes_%20Llamigos-1080p.mp4",
  },
  {
    id: "elephants-dream",
    title: "Elephants Dream",
    channelTitle: "Blender Open Movies",
    thumbnail: "https://archive.org/download/ElephantsDream/__ia_thumb.jpg",
    publishedAt: "2006-03-24T00:00:00Z",
    viewCount: "0",
    duration: "PT10M54S",
    category: "Creative coding",
    creator: "Orange Open Movie Project / Blender Foundation",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/us/",
    sourceName: "Internet Archive / Blender Open Movies",
    sourceUrl: "https://archive.org/details/ElephantsDream",
    thumbnailAttribution: "Blender Foundation via Internet Archive",
    videoUrl: "https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4",
  },
  {
    id: "spring",
    title: "Spring",
    channelTitle: "Blender Open Movies",
    thumbnail: "https://archive.org/download/spring_blenderopenmovie/__ia_thumb.jpg",
    publishedAt: "2019-10-02T00:00:00Z",
    viewCount: "0",
    duration: "PT7M44S",
    category: "Nature",
    creator: "Blender Foundation",
    license: "Public Domain Mark",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    sourceName: "Internet Archive / Blender Open Movies",
    sourceUrl: "https://archive.org/details/spring_blenderopenmovie",
    thumbnailAttribution: "Blender Foundation via Internet Archive",
    videoUrl: "https://archive.org/download/spring_blenderopenmovie/Spring%20-%20Blender%20Open%20Movie%20-%20YouTube.mp4",
  },
];
